when:
  event:
    - pull_request

steps:
  test:
      image: harbor.basilisklabs.com/docker-hub/library/rust:1.93
      commands:
        - apt-get update && apt-get install -y libssl-dev pkg-config build-essential curl libopencv-dev clang libclang-dev
        - rustc --version && cargo --version
        - cargo fetch
        - cargo test --locked --all --all-features